# Generated by Django 5.1.4 on 2025-01-09 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscriber_ip_address_subscriber_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-created_at'], 'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AddField(
            model_name='subscriber',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Available credit balance (includes coupons and refunds)', max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='subscriber',
            table='subscriber',
        ),
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_token', to='accounts.subscriber')),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='accounts_re_token_b0a1bd_idx')],
            },
        ),
    ]
