# Generated by Django 5.1.4 on 2025-01-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_subscriber_options_subscriber_credit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='is_verified',
            new_name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='last_login_ip',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='registration_attempts',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='token_expiry',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='verification_token',
        ),
        migrations.AlterModelTable(
            name='subscriber',
            table=None,
        ),
    ]
